# Generated by Django 4.0.2 on 2022-02-16 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0002_user_birthday'),
        ('the_wall_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='post',
        ),
    ]
