# Generated by Django 4.0.2 on 2022-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0002_user_birthday'),
        ('fav_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='users_who_like',
            field=models.ManyToManyField(related_name='liked_books', to='login_registration_app.User'),
        ),
    ]
